name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.3.0'

      - run: npm ci

      - run: echo "Using Powershell" && node index.js

      - run: echo "Using cmd" && node index.js
        shell: cmd
